[project]
name = "bboxareaapp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "folium>=0.20.0",
    "pyproj>=3.7.1",
    "streamlit-folium>=0.25.3",
]
